hook updated

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -3,9 +3,9 @@
 echo "Pre-commit hook started..."
 for file in $(git diff --diff-filter=d --name-only | grep -E '\.(js|jsx)$')
 do
+  echo "<----------| $file |---------->"
   node_modules/.bin/eslint "$file" --fix # we only want to lint the staged changes, not any un-staged changes
-#   if [ $? -ne 0 ]; then
-#     echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run eslint."
-#     exit 1 # exit with failure status
-#   fi
+  if [ $? -ne 0 ]; then
+    exit 1 # exit with failure status
+  fi
 done
